### ISSUE TITLE
How do I use via cli?

### ISSUE THREAD

**Issue by huzpsb** [RenardDev/OreansCrack#7]
Say, I want to run codevirtualizer /help
How do I do that?

**Comment by RenardDev** [comment]
[README.md](https://github.com/RenardDev/OreansCrack/blob/main/README.md)

**Comment by huzpsb** [comment]
> [README.md](https://github.com/RenardDev/OreansCrack/blob/main/README.md)

Sorry for the confusion I have made. What I need is to pass an argument to the CodeVirtualizer
As is mentioned here,
https://www.oreans.com/help/cv/hm_protecting-through-the-command.htm
Cv itself can be used via cli.

**Comment by huzpsb** [comment]
> [README.md](https://github.com/RenardDev/OreansCrack/blob/main/README.md)

hello? :/
